### ISSUE TITLE
Adding Bluetooth device to docker-compose

### ISSUE THREAD

**Issue by LordVoodoo** [pschmitt/docker-flickd#3]
Hello,

I managed to get this images running by docker-compose-file, unfortunately, I do not know how to add the Bluetooth device as my docker host contains hci0 and hci1.

```
  # Flic-Button Container
  flic:
    image: pschmitt/flicd
    container_name: Flic-Buttons
    restart: always
    volumes:
      - ./config:/config
      - /etc/timezone:/etc/timezone
    devices:
      - hci1 # not working
    network_mode: host
    cap_add:
      - NET_ADMIN
```
